### PR TITLE
Adding locale in Request + Leaf tag

### LINKED ISSUE #13: Issues regarding #6 and #7
Hello!
Thanks for making this Package available. It is the only package I found that allows to Localize a Vapor app.
But there are missing things, that #6 and #7 are bringing, but they are still not merged (and even outdated; I tried to implement the suggested code into a project and it gave many errors)

Any possibility to get them patched and merged?

### PR DESCRIPTION
**Pull request by nathanfallet**
This pull request is an updated version of #6 and #7 for Vapor 4 (because it was outdated; written for Vapor 3)

I also changed a bit the idea of #7, by adding a new target for Leaf (so that if you add `LingoVapor` as dependency, it does not load leaf, but if you add `LingoVaporLeaf, it does, with the custom tag)

Last, I updated the README.md to match with changes (with Vapor 4 syntax)

Fixes #13

### CODE REVIEW

**Comment by nathanfallet** [comment]
@miroslavkovac @code28 If you can have a look and give your feedback.
This changes would be a huge improvement for the library.

**Review by miroslavkovac — APPROVED** [review]
Looks good, I like the idea of creating a custom target for Vapor+Leaf.

**Comment by nathanfallet** [comment]
Yeah I though it was the best way to implement it. Thanks for merging!

**Comment by miroslavkovac** [comment]
Thanks @NathanFallet for the contribution, the changes are available in version 4.3.0.

**Comment by nathanfallet** [comment]
Localization is an essential feature to a web framework. Thanks to you for making this package available!

**Comment by code28** [comment]
Hi @NathanFallet,
it's great that you catched up with those PRs and updated it for Vapor 4!
I stopped using Leaf, so I wasn't pushing the merge of the PRs (though I applied all requested changes and don't know why they weren't merged in the first place), but I'm really glad, those were helpful for you :)

**Pull request merged**
